name: Rake and Rubocop tests

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    env:
      POSTGRES_PASSWORD: postgres
      PGHOST: 127.0.0.1
      PGUSER: postgres
      RAILS_ENV: test

    services:
      db:
        image: postgres:11.7
        ports: ['5432:5432']
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby 2.7
      uses: actions/setup-ruby@v1
      with:
        ruby-version: 2.7
    - name: Build and test with Rake
      run: |
        sudo apt-get -yqq install libpq-dev
        gem install bundler
        bundle install --jobs 4 --retry 3
        bundle exec rails db:create
        bundle exec rails db:migrate
        bundle exec rake spec
