name: Rake and Rubocop tests

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    services:
      db:
        image: postgres:11.7
        env:
          POSTGRES_PASSWORD: postgres
        ports: ['5432:5432']
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby 2.7
      uses: actions/setup-ruby@v1
      with:
        ruby-version: 2.7
    - name: Build and test with Rake
      env:
        PGHOST: 127.0.0.1
        PGPORT: ${{ job.services.postgres.ports[5432] }}
        PGUSER: postgres
        POSTGRES_PASSWORD: postgres
        PBE_DEVELOPMENT_DATABASE_PASSWORD: postgres
        RAILS_ENV: test
      run: |
        sudo apt-get -yqq install libpq-dev
        gem install bundler
        bundle install --jobs 4 --retry 3
        bundle exec rails db:create
        bundle exec rails db:migrate
        # run Spec tests
        bundle exec rake spec
        # make sure that the seed file works
        bundle exec rake db:reset db:migrate db:seed
