name: Rake and Rubocop tests

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/cache@v2
      with:
        path:
          /opt/hostedtoolcache/Ruby
          ~/.gem/
        key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
        restore-keys: |
          ${{ runner.os }}-gems-
    - name: Set up Ruby 2.7
      uses: actions/setup-ruby@v1
      with:
        ruby-version: 2.7
    - name: Run Rubocop
      run: |
        gem install rubocop
        rubocop --parallel
    - name: Run Brakeman
      run: |
        gem install brakeman
        brakeman
    - name: Setup Postgresql
      run: |
        sudo apt install postgresql
        sudo service postgresql start
        sudo -u postgres psql --command="CREATE ROLE pbe_participation_tracker WITH CREATEDB LOGIN PASSWORD 'postgres';"
        # needed for `pg` gem
        sudo apt-get -yqq install libpq-dev
    - name: Setup Rails and miscellanious
      run: |
        bundle install --jobs 4 --retry 3
        yarn install --check-files
        gem install rails
        rails webpacker:install
        gem env
        bundle env
    - name: Rails tests
      env:
        PBE_DEVELOPMENT_DATABASE_PASSWORD: postgres
        RAILS_ENV: test
      run: |
        # test plain database loading
        rails db:create db:schema:load
        # note: do not run `seeds.rb` before this
        rake spec
        # test that the database can be reset with seeds.rb
        rails db:reset
