name: Rake and Rubocop tests

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    env:
      # fixes problems with the defaults making it hard to cache
      GEM_HOME: vendor/
      BUNDLE_PATH: vendor/
      PBE_DEVELOPMENT_DATABASE_PASSWORD: postgres
      RAILS_ENV: test

    steps:
    - uses: actions/checkout@v2
    - uses: actions/cache@v2
      with:
        path: |
          vendor/
        key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
        restore-keys: |
          ${{ runner.os }}-gems-
    - name: Set up Ruby 2.7
      uses: actions/setup-ruby@v1
      with:
        ruby-version: 2.7
    - name: Run Rubocop
      run: |
        bundle install rubocop
        bundle exec rubocop --parallel
    - name: Run Brakeman
      run: |
        bundle install brakeman
        bundle exec brakeman
    - name: Setup Postgresql
      run: |
        sudo apt install postgresql
        sudo service postgresql start
        sudo -u postgres psql --command="CREATE ROLE pbe_participation_tracker WITH CREATEDB LOGIN PASSWORD 'postgres';"
        # needed for `pg` gem
        sudo apt-get -yqq install libpq-dev
    - name: Setup Rails and miscellanious
      run: |
        bundle install --jobs 4 --retry 3
        # for some reason, this needs to be done before rails installation
        yarn install --check-files
        bundle install rails
        bundle exec rails webpacker:install
    - name: Rails tests
      run: |
        # test plain database loading
        bundle exec rails db:create db:schema:load
        # note: do not run `seeds.rb` before this
        bundle exec rake spec
        # test that the database can be reset with seeds.rb
        bundle exec rails db:reset
